version: "3"
services:
    mysql_autobackup:
        build:
            context: ./
        image: mysql-autobkp:latest
        container_name: full_db_autobackup
        labels:
            - traefik.enabled=false
        env_file: .env
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - db-datavolume:/var/lib/mysql
        restart: always
volumes:
    db-datavolume:
