version: "3"
services:
    db_backup_restore:
        build:
            context: ./
        image: mysql-autobkp:latest
        container_name: db_backup_restore
        labels:
            - traefik.enabled=false
        env_file: .env
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/log/mysql-autobackup:/var/log/mysql-autobackup
            - db-datavolume:/var/lib/mysql
        restart: always
        entrypoint: "/bin/bash"
        stdin_open: true
volumes:
    db-datavolume:
