#!/bin/ash

BACKUP_FOLDER=/opt/mysql/backup
NOW=$(date +'%Y-%m-%dT%H%M%SZ')

LS=$(which ls)
GREP=$(which grep)
TAIL=$(which tail)
XARGS=$(which xargs)
RM=$(which rm)

TAIL_SIZE=$(($MYSQL_BKP_HIST_SIZE+2))

[ ! -d $BACKUP_FOLDER ] && mkdir --parents $BACKUP_FOLDER

PREFIX=$MYSQL_BACKUP_PREFIX

BASE=$BACKUP_FOLDER/$PREFIX

LAST=$BASE-$NOW

$TAR -zcvf $LAST.tar.gz $MYSQL_DATA_LOCATION

$LS -tp $BACKUP_FOLDER/ | $GREP -v '/$' | $GREP $PREFIX | $TAIL -n +$TAIL_SIZE | $XARGS -I {} $RM -- $BACKUP_FOLDER/{}
$CP $LAST.tar.gz $BASE.tar.gz
