#!/bin/bash

BACKUP_FOLDER=/tmp/mysql/backup/full
NOW=$(date +'%Y-%m-%dT%H%M%SZ')

MYSQLSH=$(which mysqlsh)
RCLONE=$(which rclone)
GZIP=$(which gzip)
TAR=$(which tar)
LS=$(which ls)
GREP=$(which grep)
TAIL=$(which tail)
XARGS=$(which xargs)
RM=$(which rm)
CP=$(which cp)
SORT=$(which sort)

TAIL_SIZE=$(($MYSQL_BACKUP_HIST_SIZE+1))

[ ! -d $BACKUP_FOLDER ] && mkdir --parents $BACKUP_FOLDER

PREFIX=$MYSQL_BACKUP_PREFIX

DEST=$BACKUP_FOLDER/$PREFIX

LAST=$DEST-$NOW

$MYSQLSH -h$MYSQL_HOST -P$MYSQL_PORT -u$MYSQL_USER -p$MYSQL_PASSWORD -- util dump-instance $LAST

$TAR -zcvf $LAST.tar.gz -C $LAST .

$CP $LAST.tar.gz $DEST.tar.gz

$RM -rf $LAST

$RCLONE copy $BACKUP_FOLDER/ $REMOTE_NAME://$REMOTE_PATH/full/ --include $PREFIX*

$RCLONE lsf $REMOTE_NAME://$REMOTE_PATH/full/ --exclude $PREFIX.tar.gz | $GREP $PREFIX | $SORT -r | $TAIL -n +$TAIL_SIZE > $BACKUP_FOLDER/old_files

$RCLONE delete $REMOTE_NAME://$REMOTE_PATH/full/ --include-from $BACKUP_FOLDER/old_files

$RM -rf $BACKUP_FOLDER
