#!/bin/bash

MYSQL_DATA_FOLDER=/var/lib/mysql

MYSQLSH=$(which mysqlsh)
LS=$(which ls)
GREP=$(which grep)
TAIL=$(which tail)
XARGS=$(which xargs)
RM=$(which rm)
RCLONE=$(which rclone)

[ ! -d $BACKUP_FOLDER ] && mkdir --parents $BACKUP_FOLDER

$RCLONE sync $MYSQL_DATA_FOLDER/ $REMOTE_NAME://$REMOTE_PATH/binlog/ --include $MYSQL_BINLOG_PREFIX*

$MYSQLSH -h$MYSQL_HOST -P$MYSQL_PORT -u$MYSQL_USER -p$MYSQL_PASSWORD --sql -e "FLUSH LOGS;"
